/**
 * PropScout AI — Seed Data
 *
 * Realistic Dutch property listings for local development and demo.
 * These are inserted into the database when the /api/seed endpoint is called.
 */

export interface SeedProperty {
  external_id: string
  source: 'pararius' | 'funda' | 'manual'
  url: string
  title: string
  price: number
  square_meters: number
  rooms: number
  property_type: 'apartment' | 'house' | 'studio'
  city: string
  neighborhood: string | null
  postal_code: string | null
  address: string | null
  year_built: number | null
  energy_label: string | null
  interior: 'furnished' | 'unfurnished' | 'upholstered' | null
  listing_status: 'active'
  images: string[]
}

export interface SeedAnalysis {
  overall_score: number
  investment_score: number
  value_score: number
  neighborhood_score: number
  wws_score: number
  wws_max_rent: number
  estimated_monthly_rent: number
  gross_yield_pct: number
  net_yield_pct: number
  ai_summary: string
  ai_pros: string[]
  ai_cons: string[]
}

export const SEED_PROPERTIES: { property: SeedProperty; analysis: SeedAnalysis }[] = [
  {
    property: {
      external_id: 'seed-ams-001',
      source: 'pararius',
      url: 'https://www.pararius.com/apartment-for-rent/amsterdam/12345/herengracht',
      title: 'Herengracht 234, Amsterdam',
      price: 425000,
      square_meters: 68,
      rooms: 3,
      property_type: 'apartment',
      city: 'Amsterdam',
      neighborhood: 'Grachtengordel-West',
      postal_code: '1016 BX',
      address: 'Herengracht 234',
      year_built: 1890,
      energy_label: 'B',
      interior: 'upholstered',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 72,
      investment_score: 68,
      value_score: 78,
      neighborhood_score: 85,
      wws_score: 168,
      wws_max_rent: 0,
      estimated_monthly_rent: 1850,
      gross_yield_pct: 5.22,
      net_yield_pct: 3.87,
      ai_summary: 'This 68 m\u00B2 canal belt apartment offers a solid gross yield above 5%, exceeding the Amsterdam average. The free-market rental segment provides full rent-setting flexibility. The thin cashflow buffer warrants careful vacancy planning.',
      ai_pros: [
        'Gross yield of 5.22% exceeds Amsterdam average of 4.2%',
        'Free-market segment \u2014 no rent regulation cap',
        'Canal belt location ensures strong tenant demand year-round',
        'Energy label B reduces utility costs and improves appeal',
      ],
      ai_cons: [
        'Monthly cashflow of \u20AC431 leaves limited margin for vacancies',
        'Transfer tax adds \u20AC17,000 to entry costs',
        'VvE reserves should be independently verified',
        'Monument status may limit renovation options',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-rot-001',
      source: 'funda',
      url: 'https://www.funda.nl/koop/rotterdam/appartement-56789-witte-de-withstraat-45/',
      title: 'Witte de Withstraat 45, Rotterdam',
      price: 245000,
      square_meters: 82,
      rooms: 3,
      property_type: 'apartment',
      city: 'Rotterdam',
      neighborhood: 'Cool',
      postal_code: '3012 BM',
      address: 'Witte de Withstraat 45',
      year_built: 1935,
      energy_label: 'C',
      interior: 'unfurnished',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 81,
      investment_score: 82,
      value_score: 85,
      neighborhood_score: 70,
      wws_score: 155,
      wws_max_rent: 0,
      estimated_monthly_rent: 1476,
      gross_yield_pct: 7.23,
      net_yield_pct: 5.41,
      ai_summary: 'Excellent value proposition in Rotterdam\'s trendy Cool district. At \u20AC2,988/m\u00B2, this is well below the Rotterdam average. The 7.2% gross yield is exceptional for a Randstad city. Strong rental demand from young professionals.',
      ai_pros: [
        'Outstanding gross yield of 7.23% \u2014 well above urban average',
        'Price of \u20AC2,988/m\u00B2 is 27% below Rotterdam average',
        'Cool district is one of Rotterdam\'s most sought-after neighborhoods',
        'Free-market rental \u2014 no WWS rent cap applies',
      ],
      ai_cons: [
        'Pre-war building (1935) may have higher maintenance costs',
        'Energy label C \u2014 upgrade to B/A could improve WWS score and appeal',
        'Street-level noise from nightlife district may affect tenants',
        'Rotterdam market more volatile than Amsterdam in downturns',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-utr-001',
      source: 'pararius',
      url: 'https://www.pararius.com/apartment-for-rent/utrecht/23456/oudegracht',
      title: 'Oudegracht 156, Utrecht',
      price: 365000,
      square_meters: 75,
      rooms: 3,
      property_type: 'apartment',
      city: 'Utrecht',
      neighborhood: 'Binnenstad',
      postal_code: '3511 AL',
      address: 'Oudegracht 156',
      year_built: 1920,
      energy_label: 'B',
      interior: 'upholstered',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 74,
      investment_score: 70,
      value_score: 72,
      neighborhood_score: 85,
      wws_score: 162,
      wws_max_rent: 0,
      estimated_monthly_rent: 1650,
      gross_yield_pct: 5.42,
      net_yield_pct: 3.98,
      ai_summary: 'Charming Oudegracht apartment in Utrecht\'s historic center. The 5.4% gross yield is solid for this premium location. Utrecht\'s university city status ensures consistent tenant demand.',
      ai_pros: [
        'Gross yield of 5.42% is strong for Utrecht city center',
        'Oudegracht is the most prestigious address in Utrecht',
        'University city status provides year-round tenant demand',
        'Energy label B adds to long-term value proposition',
      ],
      ai_cons: [
        'Utrecht prices have risen sharply \u2014 limited further upside',
        'Canal-side buildings require careful moisture inspection',
        'VvE costs for historic buildings tend to be above average',
        'Limited parking options may narrow tenant pool',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-dh-001',
      source: 'funda',
      url: 'https://www.funda.nl/koop/den-haag/appartement-34567-statenkwartier/',
      title: 'Frederik Hendriklaan 89, Den Haag',
      price: 295000,
      square_meters: 85,
      rooms: 4,
      property_type: 'apartment',
      city: 'Den Haag',
      neighborhood: 'Statenkwartier',
      postal_code: '2582 GA',
      address: 'Frederik Hendriklaan 89',
      year_built: 1910,
      energy_label: 'C',
      interior: 'unfurnished',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 78,
      investment_score: 76,
      value_score: 80,
      neighborhood_score: 70,
      wws_score: 170,
      wws_max_rent: 0,
      estimated_monthly_rent: 1615,
      gross_yield_pct: 6.57,
      net_yield_pct: 4.82,
      ai_summary: 'Spacious 4-room apartment in Den Haag\'s upscale Statenkwartier. At \u20AC3,471/m\u00B2, this offers good value for the area. The 6.6% gross yield and healthy cashflow make this an attractive investment.',
      ai_pros: [
        'Gross yield of 6.57% is excellent for The Hague',
        'Statenkwartier is a high-demand expat neighborhood',
        '4 rooms at 85 m\u00B2 appeals to families and professionals',
        'International organizations nearby ensure stable demand',
      ],
      ai_cons: [
        'Energy label C \u2014 upgrading adds cost but improves WWS score',
        'Pre-war construction (1910) requires thorough inspection',
        'Den Haag market relies heavily on government/diplomatic sector',
        'Transfer tax of 2% adds \u20AC5,900 to acquisition costs',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-ehv-001',
      source: 'funda',
      url: 'https://www.funda.nl/koop/eindhoven/appartement-45678-strijp/',
      title: 'Torenallee 22, Eindhoven',
      price: 275000,
      square_meters: 78,
      rooms: 3,
      property_type: 'apartment',
      city: 'Eindhoven',
      neighborhood: 'Strijp-S',
      postal_code: '5617 BD',
      address: 'Torenallee 22',
      year_built: 2018,
      energy_label: 'A',
      interior: 'upholstered',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 83,
      investment_score: 79,
      value_score: 82,
      neighborhood_score: 70,
      wws_score: 185,
      wws_max_rent: 0,
      estimated_monthly_rent: 1326,
      gross_yield_pct: 5.79,
      net_yield_pct: 4.28,
      ai_summary: 'Modern apartment in Eindhoven\'s trendy Strijp-S tech district. Built in 2018 with energy label A, this property offers low maintenance costs and strong appeal to tech professionals working at ASML, Philips, and the High Tech Campus.',
      ai_pros: [
        'Energy label A means minimal utility costs and maximum WWS score',
        'Strijp-S is Eindhoven\'s fastest-appreciating neighborhood',
        'Modern construction (2018) means low maintenance for years',
        'Tech sector employment drives consistent high-quality demand',
      ],
      ai_cons: [
        'Eindhoven rents are lower than Randstad \u2014 caps income potential',
        'Strijp-S has significant new supply pipeline that may compress rents',
        'Tech sector concentration creates dependency risk',
        'VvE contributions on newer buildings can escalate quickly',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-gro-001',
      source: 'pararius',
      url: 'https://www.pararius.com/apartment-for-rent/groningen/67890/oosterstraat',
      title: 'Oosterstraat 34, Groningen',
      price: 195000,
      square_meters: 65,
      rooms: 2,
      property_type: 'apartment',
      city: 'Groningen',
      neighborhood: 'Binnenstad',
      postal_code: '9711 NR',
      address: 'Oosterstraat 34',
      year_built: 1965,
      energy_label: 'C',
      interior: 'unfurnished',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 76,
      investment_score: 80,
      value_score: 78,
      neighborhood_score: 55,
      wws_score: 130,
      wws_max_rent: 709,
      estimated_monthly_rent: 1040,
      gross_yield_pct: 6.4,
      net_yield_pct: 4.72,
      ai_summary: 'Affordable 2-room apartment in Groningen\'s city center with an impressive 6.4% gross yield. The student city dynamics ensure near-zero vacancy. Note: at 130 WWS points, this falls in the regulated segment with a \u20AC709 max rent.',
      ai_pros: [
        'Gross yield of 6.4% is excellent for northern Netherlands',
        'Groningen has the lowest vacancy rate in the country',
        'Entry price under \u20AC200K minimizes capital exposure',
        'University city with 60,000+ students ensures demand',
      ],
      ai_cons: [
        'WWS score of 130 points \u2014 regulated segment with \u20AC709 max rent cap',
        'Current rent of \u20AC1,040 exceeds the regulated maximum \u2014 risk of tenant complaint',
        'Energy label C limits WWS points \u2014 upgrade could lift above threshold',
        'Groningen market is less liquid than Randstad cities',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-hrl-001',
      source: 'funda',
      url: 'https://www.funda.nl/koop/haarlem/appartement-78901-barteljorisstraat/',
      title: 'Barteljorisstraat 12, Haarlem',
      price: 385000,
      square_meters: 72,
      rooms: 3,
      property_type: 'apartment',
      city: 'Haarlem',
      neighborhood: 'Centrum',
      postal_code: '2012 JB',
      address: 'Barteljorisstraat 12',
      year_built: 1895,
      energy_label: 'B',
      interior: 'upholstered',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 70,
      investment_score: 63,
      value_score: 68,
      neighborhood_score: 85,
      wws_score: 158,
      wws_max_rent: 0,
      estimated_monthly_rent: 1728,
      gross_yield_pct: 5.38,
      net_yield_pct: 3.72,
      ai_summary: 'Historic Haarlem center apartment with a reasonable 5.4% yield. The premium location near the Grote Markt commands top rents, but the \u20AC5,347/m\u00B2 price is in line with the Haarlem average, limiting value upside.',
      ai_pros: [
        'Haarlem center is one of the most desirable addresses in North Holland',
        'Free-market segment with no rent cap',
        '15 min by train to Amsterdam attracts commuter tenants',
        'Energy label B is good for a 19th-century building',
      ],
      ai_cons: [
        'Price of \u20AC5,347/m\u00B2 offers limited value discount',
        'Monthly cashflow margin is tight at \u20AC309',
        'Monument status may restrict renovations',
        'Haarlem market closely tracks Amsterdam \u2014 high entry point',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-ams-002',
      source: 'funda',
      url: 'https://www.funda.nl/koop/amsterdam/appartement-11111-de-pijp/',
      title: 'Ferdinand Bolstraat 178, Amsterdam',
      price: 325000,
      square_meters: 48,
      rooms: 2,
      property_type: 'apartment',
      city: 'Amsterdam',
      neighborhood: 'De Pijp',
      postal_code: '1072 LT',
      address: 'Ferdinand Bolstraat 178',
      year_built: 1925,
      energy_label: 'C',
      interior: 'unfurnished',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 67,
      investment_score: 58,
      value_score: 62,
      neighborhood_score: 85,
      wws_score: 125,
      wws_max_rent: 681,
      estimated_monthly_rent: 1344,
      gross_yield_pct: 4.96,
      net_yield_pct: 3.08,
      ai_summary: 'Compact De Pijp apartment at \u20AC6,771/m\u00B2 \u2014 above Amsterdam average. At 125 WWS points, this falls in the regulated segment with a \u20AC681 max rent, significantly below the market rent of \u20AC1,344. High regulatory risk.',
      ai_pros: [
        'De Pijp is one of Amsterdam\'s most popular neighborhoods',
        'Strong capital appreciation potential in premium location',
        'Compact units have lowest vacancy rates',
        '2-room layout appeals to young professionals \u2014 largest demographic',
      ],
      ai_cons: [
        'CRITICAL: WWS score of 125 puts this in regulated segment (max \u20AC681)',
        'Market rent of \u20AC1,344 far exceeds regulated max \u2014 tenant complaint risk',
        'Price of \u20AC6,771/m\u00B2 is above Amsterdam average \u2014 limited value',
        'Energy label C upgrade needed to potentially reach free-market threshold',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-lei-001',
      source: 'pararius',
      url: 'https://www.pararius.com/apartment-for-rent/leiden/22222/rapenburg',
      title: 'Rapenburg 45, Leiden',
      price: 340000,
      square_meters: 70,
      rooms: 3,
      property_type: 'apartment',
      city: 'Leiden',
      neighborhood: 'Binnenstad',
      postal_code: '2311 EV',
      address: 'Rapenburg 45',
      year_built: 1880,
      energy_label: 'B',
      interior: 'upholstered',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 75,
      investment_score: 71,
      value_score: 74,
      neighborhood_score: 70,
      wws_score: 160,
      wws_max_rent: 0,
      estimated_monthly_rent: 1470,
      gross_yield_pct: 5.19,
      net_yield_pct: 3.78,
      ai_summary: 'Prestigious Rapenburg address in Leiden\'s university heart. At \u20AC4,857/m\u00B2, this is slightly below the Leiden center average. The 5.2% yield is solid, backed by consistent demand from university staff and students.',
      ai_pros: [
        'Rapenburg is Leiden\'s most prestigious canal \u2014 trophy address',
        'Free-market segment with strong pricing power',
        'Leiden University drives constant tenant demand',
        'Bioscience cluster (LUMC, BioPartner) adds professional demand',
      ],
      ai_cons: [
        'Cashflow buffer of \u20AC368 is moderate',
        'Historic building (1880) needs thorough structural inspection',
        'Leiden rents are lower than Amsterdam despite price proximity',
        'Student housing regulations could affect market dynamics',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-rot-002',
      source: 'pararius',
      url: 'https://www.pararius.com/apartment-for-rent/rotterdam/33333/kop-van-zuid',
      title: 'Wilhelminakade 88, Rotterdam',
      price: 350000,
      square_meters: 90,
      rooms: 4,
      property_type: 'apartment',
      city: 'Rotterdam',
      neighborhood: 'Kop van Zuid',
      postal_code: '3072 AP',
      address: 'Wilhelminakade 88',
      year_built: 2010,
      energy_label: 'A',
      interior: 'upholstered',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 80,
      investment_score: 76,
      value_score: 78,
      neighborhood_score: 70,
      wws_score: 195,
      wws_max_rent: 0,
      estimated_monthly_rent: 1620,
      gross_yield_pct: 5.55,
      net_yield_pct: 4.11,
      ai_summary: 'Modern 4-room apartment in Rotterdam\'s flagship Kop van Zuid development. At \u20AC3,889/m\u00B2, this is slightly below the area average. Energy label A and 2010 construction mean low running costs. The waterfront location commands premium rents.',
      ai_pros: [
        'Kop van Zuid is Rotterdam\'s premier waterfront neighborhood',
        'Modern construction (2010) with energy label A \u2014 minimal costs',
        '4 rooms at 90 m\u00B2 attracts high-income professional tenants',
        'Well above WWS threshold \u2014 solidly in free-market segment',
      ],
      ai_cons: [
        'Rotterdam waterfront has increasing new construction supply',
        'Service charges on modern high-rises tend to be above average',
        'Gross yield of 5.55% is good but not exceptional for Rotterdam',
        'Area dependent on continued corporate/office development',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-ams-003',
      source: 'funda',
      url: 'https://www.funda.nl/koop/amsterdam/huis-44444-jordaan/',
      title: 'Bloemgracht 67, Amsterdam',
      price: 575000,
      square_meters: 95,
      rooms: 4,
      property_type: 'house',
      city: 'Amsterdam',
      neighborhood: 'Jordaan',
      postal_code: '1015 TK',
      address: 'Bloemgracht 67',
      year_built: 1870,
      energy_label: 'C',
      interior: 'unfurnished',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 65,
      investment_score: 55,
      value_score: 58,
      neighborhood_score: 85,
      wws_score: 180,
      wws_max_rent: 0,
      estimated_monthly_rent: 2660,
      gross_yield_pct: 5.55,
      net_yield_pct: 3.45,
      ai_summary: 'Iconic Jordaan canal house with premium lifestyle appeal but moderate investment returns. At \u20AC6,053/m\u00B2, the price is below the Jordaan average, but the high absolute price means significant capital commitment for a 5.6% yield.',
      ai_pros: [
        'Jordaan is Amsterdam\'s most iconic and resilient neighborhood',
        'House format is rare in Amsterdam \u2014 premium scarcity value',
        '95 m\u00B2 with 4 rooms attracts high-income families and expats',
        'Strong long-term capital appreciation in Amsterdam center',
      ],
      ai_cons: [
        'High absolute price of \u20AC575K increases capital at risk',
        'Monthly cashflow buffer is modest relative to investment size',
        '1870 construction \u2014 structural and moisture risks are elevated',
        'Energy label C on historic property is expensive to improve',
      ],
    },
  },
  {
    property: {
      external_id: 'seed-del-001',
      source: 'funda',
      url: 'https://www.funda.nl/koop/delft/appartement-55555-centrum/',
      title: 'Oude Delft 78, Delft',
      price: 310000,
      square_meters: 72,
      rooms: 3,
      property_type: 'apartment',
      city: 'Delft',
      neighborhood: 'Centrum',
      postal_code: '2611 CD',
      address: 'Oude Delft 78',
      year_built: 1900,
      energy_label: 'B',
      interior: 'upholstered',
      listing_status: 'active',
      images: [],
    },
    analysis: {
      overall_score: 76,
      investment_score: 73,
      value_score: 75,
      neighborhood_score: 70,
      wws_score: 158,
      wws_max_rent: 0,
      estimated_monthly_rent: 1440,
      gross_yield_pct: 5.57,
      net_yield_pct: 4.05,
      ai_summary: 'Well-located Delft center apartment at a reasonable \u20AC4,306/m\u00B2. TU Delft and TNO ensure consistent professional demand. The 5.6% gross yield and healthy cashflow make this a balanced investment.',
      ai_pros: [
        'TU Delft (30,000 students) and TNO create deep tenant demand',
        'Gross yield of 5.57% is attractive for South Holland',
        'Delft center is compact and walkable \u2014 very high livability',
        'Energy label B keeps the property above WWS threshold',
      ],
      ai_cons: [
        'Delft market is small \u2014 fewer exit options than larger cities',
        'Historic building (1900) requires careful VvE inspection',
        'Student housing regulations may tighten in coming years',
        'Proximity to The Hague means competition for professional tenants',
      ],
    },
  },
]
